version: "3.9"

services:
  api:
    build: .
    container_name: api
    volumes:
      - ./src:/app
      - media_volume:/media/
      - static_volume:/static/
    command: >
      bash -c "
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py createsuperuser --no-input; 
      python manage.py runserver 0.0.0.0:8000 "
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail -s http://localhost:8000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always


volumes:
  media_volume:
    name: api_media
  static_volume:
    name: api_static
