version: "3.9"

services:
  api:
    build: .
    container_name: api
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    command: >
      bash -c "
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py createsuperuser --no-input; 
      python manage.py collectstatic --no-input;
      python manage.py runserver 0.0.0.0:8000 "
    env_file:
      - ./.env
#    ports:
#      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8000/api/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: postgres:16.0-alpine
    container_name: db
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
#    ports:
#      - "5439:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 2s
      retries: 5
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/src/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always



volumes:
  db_volume:
    name: api_db
  media_volume:
    name: api_media
  static_volume:
    name: api_static
