version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./src:/app
    command: >
      bash -c " python manage.py runserver localhost:8000 "
    env_file:
      - ./.env
    ports:
      - "8000:8000"
