# Generated by Django 4.2.7 on 2024-02-07 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='categories',
                        to='utils.image',
                        verbose_name='Зображення',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='subs',
                        to='products.category',
                        verbose_name='Батьківська Категорія',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                (
                    'stock',
                    models.CharField(
                        choices=[
                            ('in_stock', 'Є в наявності'),
                            ('out_of_stock', 'Немає в наявності'),
                            ('to_order', 'Під замовлення'),
                        ],
                        default='in_stock',
                        max_length=20,
                        verbose_name='Склад',
                    ),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Відображення')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='products',
                        to='products.category',
                        verbose_name='Категорія',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'all_attributes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='specifications',
                        to='utils.attribute',
                        verbose_name='Всі Характеристики',
                    ),
                ),
                (
                    'card_attributes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='_card_specifications',
                        to='utils.attribute',
                        verbose_name='Характеристики Картки',
                    ),
                ),
                (
                    'detail_attributes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='_detail_specifications',
                        to='utils.attribute',
                        verbose_name='Характеристики Детальної Сторінки',
                    ),
                ),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specification',
                        to='products.product',
                        verbose_name='Продукт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Технічні Характеристики',
                'verbose_name_plural': 'Технічні Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProductImageSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('images', models.ManyToManyField(blank=True, to='utils.image', verbose_name='Зображення')),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_set',
                        to='products.product',
                        verbose_name='Набір Зображень',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Набір Зображень Продукту',
                'verbose_name_plural': 'Набори Зображень Продуктів',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prices',
                        to='products.product',
                        verbose_name='Продукт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ціна',
                'verbose_name_plural': 'Ціни',
            },
        ),
    ]
