# Generated by Django 4.2.7 on 2024-01-15 10:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                (
                    'parent',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
