# Generated by Django 4.2.7 on 2024-02-01 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
    ]
