# Generated by Django 4.2.7 on 2024-01-17 09:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('images', models.ManyToManyField(blank=True, to='utils.image')),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='products.product'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
