# Generated by Django 4.2.7 on 2024-01-16 10:29

from django.db import migrations, models

from products.models import _set_grade_dict


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.JSONField(default=_set_grade_dict),
        ),
    ]
