# Generated by Django 4.2.7 on 2024-02-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0001_initial'),
        ('products', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimageset',
            name='cover_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='_image_set',
                to='utils.image',
                verbose_name='Cover Image',
            ),
        ),
    ]
