# Generated by Django 4.2.7 on 2024-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Title'),
        ),
    ]
