# Generated by Django 4.2.7 on 2024-01-15 13:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'stock',
                    models.CharField(
                        choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('to_order', 'To order')],
                        default='in_stock',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField()),
                ('is_displayed', models.BooleanField(default=True)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
