# Generated by Django 4.2.7 on 2024-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_alter_productimageset_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
