# Generated by Django 4.2.7 on 2024-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
