# Generated by Django 4.2.7 on 2024-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
