# Generated by Django 4.2.7 on 2024-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0001_initial'),
        ('products', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='specifications', to='utils.attribute'),
        ),
    ]
