# Generated by Django 4.2.7 on 2024-01-15 14:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('attributes', models.ManyToManyField(related_name='specifications', to='products.attribute')),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.product'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
