# Generated by Django 4.2.7 on 2024-01-26 15:28

from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'delivery',
                    models.CharField(
                        choices=[('pickup', 'Pickup'), ('nova_post', 'Nova post')], default='pickup', max_length=50
                    ),
                ),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'payment',
                    models.CharField(
                        choices=[
                            ('visa', 'Visa'),
                            ('mastercard', 'Mastercard'),
                            ('cash_on_delivery', 'Cash on delivery'),
                        ],
                        default='cash_on_delivery',
                        max_length=50,
                    ),
                ),
                ('is_paid', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_processing', 'In processing'),
                            ('completed', 'Completed'),
                            ('canceled', 'Canceled'),
                        ],
                        default='in_processing',
                        max_length=50,
                    ),
                ),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order'
                    ),
                ),
                (
                    'price',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.price',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.product',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', orders.models.PhoneField(max_length=50, null=True)),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='orders.order'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
