# Generated by Django 4.2.7 on 2024-02-07 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models
import orders.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                (
                    'delivery',
                    models.CharField(
                        choices=[('pickup', 'Самовивіз'), ('nova_post', 'Нова Пошта')],
                        default='pickup',
                        max_length=50,
                        verbose_name='Спосіб Доставки',
                    ),
                ),
                (
                    'delivery_address',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса Доставки'),
                ),
                (
                    'payment',
                    models.CharField(
                        choices=[
                            ('visa', 'Visa'),
                            ('mastercard', 'Mastercard'),
                            ('cash_on_delivery', 'Накладений Платіж'),
                        ],
                        default='cash_on_delivery',
                        max_length=50,
                        verbose_name='Оплата',
                    ),
                ),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачений')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_processing', 'Обробляється'),
                            ('completed', 'Виконаний'),
                            ('canceled', 'Відмінений'),
                        ],
                        default='in_processing',
                        max_length=50,
                        verbose_name='Статус',
                    ),
                ),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість'
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='orders.order',
                        verbose_name='Замовлення',
                    ),
                ),
                (
                    'price',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.price',
                        verbose_name='Ціна',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.product',
                        verbose_name='Продукт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Замовлений Продукт',
                'verbose_name_plural': 'Замовлені Продукти',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'full_name',
                    models.CharField(
                        max_length=100,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(3), orders.validators.validate_name],
                        verbose_name="Прізвище та Ім'я",
                    ),
                ),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Електронна пошта')),
                ('phone', orders.models.PhoneField(max_length=50, null=True, verbose_name='Телефон')),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer',
                        to='orders.order',
                        verbose_name='Замовлення',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
    ]
