# Generated by Django 4.2.7 on 2024-01-23 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'delivery',
                    models.CharField(
                        choices=[('pickup', 'Pickup'), ('nova_post', 'Nova post')], default='pickup', max_length=50
                    ),
                ),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'payment',
                    models.CharField(
                        choices=[
                            ('visa', 'Visa'),
                            ('mastercard', 'Mastercard'),
                            ('cash_on_delivery', 'Cash on delivery'),
                        ],
                        default='cash_on_delivery',
                        max_length=50,
                    ),
                ),
                ('is_paid', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('in_processing', 'In processing'),
                            ('completed', 'Completed'),
                            ('canceled', 'Canceled'),
                        ],
                        default='in_processing',
                        max_length=50,
                    ),
                ),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
