# Generated by Django 4.2.7 on 2024-02-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'
            ),
        ),
    ]
