# Generated by Django 4.2.7 on 2024-02-11 08:17

import django.core.validators
from django.db import migrations, models
import orders.models
import orders.validators


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3), orders.validators.validate_name],
                verbose_name="Прізвище та Ім'я",
            ),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=orders.models.PhoneField(max_length=50, verbose_name='Телефон'),
        ),
    ]
