# Generated by Django 4.2.7 on 2024-02-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_products',
                to='products.price',
                verbose_name='Price',
            ),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_products',
                to='products.product',
                verbose_name='Product',
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer',
                to='orders.order',
                verbose_name='Order',
            ),
        ),
    ]
