# Generated by Django 4.2.7 on 2024-01-23 12:46

from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', orders.models.PhoneField(max_length=50)),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='orders.order'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
