# Generated by Django 4.2.7 on 2024-02-03 14:59

import django.core.validators
from django.db import migrations, models

from orders.validators import validate_name


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(
                max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), validate_name]
            ),
        ),
    ]
