# Generated by Django 4.2.7 on 2024-01-23 12:58

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=orders.models.PhoneField(max_length=50, null=True),
        ),
    ]
