# Generated by Django 4.2.7 on 2024-01-23 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_alter_category_uuid_alter_price_uuid_and_more'),
        ('orders', '0003_alter_customer_email_alter_customer_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'
                    ),
                ),
                (
                    'price',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.price',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_products',
                        to='products.product',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
