# Generated by Django 4.2.7 on 2024-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
    ]
