# Generated by Django 4.2.7 on 2024-01-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
